### ISSUE TITLE
2.4 Incompatibility

### ISSUE THREAD

**Issue by brightonmike** [genecommerce/module-kraken#6]
```
magento/module-config 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.4.7) does not satisfy that requirement.
```

**Comment by cjnewbs** [comment]
@brightonmike Created a branch: `gene/module-kraken:dev-feature/2.4-compatibility`. This will allow you to install. I have yet to test, but will be reviewing, testing and tagging/releasing later this week.
